###
DELETE http://localhost:3000/api/users/73835ad6-dd22-4971-b805-45fcbaa14143
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZW11c2siLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTY5NTkyODI5MiwiZXhwIjoxNjk1OTI5NDkyfQ.8FC5fr94DxyKlCQsNxXoyV31jfOwnDN63P1fGJKncKI

###
GET http://localhost:3000/api/users/73835ad6-dd22-4971-b805-45fcbaa14143
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZW11c2siLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTY5NTkyODI5MiwiZXhwIjoxNjk1OTI5NDkyfQ.8FC5fr94DxyKlCQsNxXoyV31jfOwnDN63P1fGJKncKI
###

#

###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "username":"emusk",
  "password":"123"
}

###
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "username":"emusk",
  "password":"123"
}

###
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZW11c2siLCJwYXNzd29yZCI6IjEyMyIsImlhdCI6MTc0MjA5MzcwNywiZXhwIjoxNzQyMDk0OTA3fQ.2iL-CAevw1XuG5QWjJs_JXeUMyWiOtOXa9c14WhSi9c


###
POST http://localhost:3001/api/token/
Content-Type: application/json


{
  "username":"emusk",
  "password":"123"
}
